---
title: "figure4"
output: html_document
date: "2025-09-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(Seurat)
library(scRepertoire)
library(VDJdive)
library(rstatix)
library(readxl)
library(ggpubr)

source("/home/Desktop/R_tools/ECLIPSE.R")
source("/home/Desktop/R_tools/VDJdive_ECLIPSE_paperFunctions.R")
set.seed(16)
```

```{r}
############################################################################
###                         Pre-Processing                               ###
############################################################################

braun <- readRDS("/home/Desktop/braun/rotation/Braun_cancer_cell/scRCC_SeuratObject.rds")

braun@meta.data <- braun@meta.data %>% separate(Sample, into = c("donor", "tissue"), remove = FALSE, sep = "_")
braun@meta.data <- braun@meta.data %>% mutate(tissue = case_when(
                                                                 tissue %in% c("T", "T2") ~ "Tumor",
                                                                 tissue == "N" ~ "Normal",
                                                                 tissue %in% c("M", "V")  ~ "Other"))

cd8 <- subset(braun, subset = ClusterName_TCells %in% c("Treg", "Activated CD4.1", "Activated CD4.2", "CD4 TCM.1", "CD4 TCM.2", "Mito-high T cells", "-1"), invert = TRUE)

dirs <- list.files("/gpfs/gibbs/pi/braun/braun_cancerCell/realignment", recursive = TRUE, pattern = "all_contig_annotations\\.csv$", full.names = TRUE)
dirs <- dirs[!str_detect(dirs, "SC_VDJ_ASSEMBLER_CS")]
dirs <- str_replace(dirs, "all.*$", "")

matching <- read.csv("/home/project/david/sc_datasets/braun_cancer_cell/braun_matching2.csv")
matching <- matching %>% filter(Sample != "")

cd8@meta.data <- cd8@meta.data %>% left_join(matching[, 2:3], by = "Sample")
cd8@meta.data <- as.data.frame(cd8@meta.data)
rownames(cd8@meta.data) <- cd8$Cell_barcode
cd8$Cell_Barcode <- str_replace(cd8$Cell_barcode, "\\-.*$", "-1")

ElbowPlot(cd8, ndims = 50)
cd8 <- RunUMAP(cd8, dims = 1:30)

cd8$ClusterName_TCells[cd8$ClusterName_TCells == "PMCH+ terminally Exhausted CD8.1"] <- "PMCH+ terminally \n Exhausted CD8.1"
cd8$ClusterName_TCells[cd8$ClusterName_TCells == "Terminally exhausted CD8.2"] <- "Terminally \n exhausted CD8.2"
cd8$ClusterName_TCells[cd8$ClusterName_TCells == "Terminally exhausted CD8.3"] <- "Terminally \n exhausted CD8.3"

cd8s <- ECLIPSE(folders = dirs, file_type = "all", seurat_object = cd8, batch = "index", donor = "donor", group = "donor", original_barcode = "Cell_Barcode", write_folder = "/home/Desktop/braun/ECLIPSE/braun_cCell/tcr_temp", mode = "standard")

cd8s <- tcrDoubletDetect(cd8s)
```

```{r}
############################################################################
###                             Figure 4A                                ###
############################################################################


### Defining the cells that are suitable for this. They must have 2 chains, with 1 TCRa and 1 TCRb
set.seed(16)
cd8s@meta.data <- cd8s@meta.data %>% mutate(suitable = case_when(
                                                                 scr_count == 2 & !is.na(CTaa) & !str_detect(scR_CTaa, ";") ~ TRUE,
                                                                 TRUE ~ FALSE))
cd8s@meta.data <- cd8s@meta.data %>% filter(suitable) %>% distinct(Cell_barcode) %>% mutate(pos = sample.int(n())) %>% right_join(cd8s@meta.data, by = "Cell_barcode")

### Running the pro-processing of ECLIPSE. Pre is just all the cleaning, and then returns the output
threeA <- pre(folders = dirs, file_type = "all", seurat_object = cd8, batch = "index", donor = "donor", group = "tissue", original_barcode = "Cell_Barcode", write_folder = "/home/ecb86/Desktop/braun/tcrEclipse/braun_cCell/tcr_temp", mode = "standard", format = "Blank")

### Extracting the outputs from pre.
contigs <- threeA[[1]]
obj <- threeA[[2]]

### Finding suitable barcodes
suitable_barcodes <- (cd8s@meta.data %>% filter(suitable) %>% select(Cell_barcode))$Cell_barcode

### Giving them a unique key for joining, before removing unsuitable cells.
contigs <- contigs %>% unite(c(barcode, cdr3), sep = "_", remove = FALSE, col = "key")
n_distinct(contigs$key) == nrow(contigs)
contigs <- contigs %>% distinct(key) %>% mutate(pos = sample.int(n())) %>% left_join(contigs, by = "key")
contigs$suitable <- contigs$barcode %in% suitable_barcodes

### Considering only contigs that aren't doublets and have the lowest pos variable in their cell which is used for randomization. This ensures 2 contigs aren't removed from the same cell.
### Then selecting only 500 contigs to remove and retaining only the key
contigs2 <- contigs %>% filter(barcode %in% cd8s$Cell_barcode) %>% 
                        group_by(barcode) %>% filter(pos == min(pos)) %>% ungroup() %>%
                        filter(suitable) %>% arrange(desc(pos))
contigs2 <- contigs2 %>% filter(row_number() <= 500)
contigs2 <- contigs2$key

### Removing those 500 contigs from the original contigs file, and removing extra columns
contigs3 <- contigs %>% filter(key %in% contigs2 == FALSE)
contigs3 <- contigs3 %>% select(-pos, -key)


### Taking the new contigs (reduced by 500) and running them through the second half ECLIPSE pipeline
pst <- post(folders = dirs, all = contigs3, seurat_object = obj, batch = "index", donor = "donor", group = "tissue", original_barcode = "Cell_Barcode", write_folder = "/home/Desktop/braun/tcrEclipse/braun_cCell/tcr_temp", mode = "standard")

### Extracting the new clone call and whether it was called by VDJdive or not. Then joining to the regular seurat object for comparison with/without the 500 contigs.
pst2 <- pst %>% select(Cell_barcode, "new_CTaa" = CTaa, "new_scrCTaa" = scR_CTaa, "newCloneCall" = cloneCallSource)
join <- cd8s@meta.data %>% left_join(pst2, by = "Cell_barcode")

### Defining whether each cell was changed and the condition it was in
altered_barcodes <- str_replace(contigs2, "_.*$", "")
join <- join %>% mutate(altered = case_when(
                                             Cell_barcode %in% altered_barcodes ~ TRUE,
                                             !Cell_barcode %in% altered_barcodes ~ FALSE),
                        steady = case_when(
                                           CTaa == new_CTaa ~ "Same Call",
                                           CTaa != new_CTaa & newCloneCall == "scRepertoire" ~ "Call Now\nAmbiguous",
                                           CTaa != new_CTaa & newCloneCall == "VDJdive" ~ "New Call"))

### Calculating the percentages of each for each group
join2 <- join %>% filter(!is.na(steady) & !is.na(altered)) %>% group_by(altered) %>% mutate(altered_count = n()) %>% ungroup() %>% 
                                                               group_by(altered, steady) %>% summarise(pct = 100 * n() / first(altered_count),
                                                                                                       count = n(),
                                                                                                       altered_count = first(altered_count))

### Making graph
join2$steady <- factor(join2$steady, levels = c("New Call", "Call Now\nAmbiguous", "Same Call"))

join2 %>% ggplot() + geom_col(aes(x = altered, y = pct, fill = steady)) + theme_classic() +
                     ylab("% of Cells") + xlab("TCR Chain\nRemoval") +
                     theme(axis.title = element_text(size = 20, face = "bold"), legend.text = element_text(size = 14, face = "bold"), axis.ticks.x = element_blank(), 
                           legend.title = element_text(face = "bold", size = 14), axis.text = element_text(size = 14, face = "bold"), axis.text.x = element_text(size = 24, face = "bold")) +
                     scale_y_continuous(expand = c(0.01, 0.01), breaks = seq(0, 100, 10), labels = c(0, "", 20, "", 40, "", 60, "", 80, "", 100)) + 
                     labs(fill = "Impact on\nPredicted\nClonotype") + scale_x_discrete(labels = c("-", "+")) +
                     scale_fill_manual(values = c("yellow3", "chartreuse4", "dodgerblue4"),
                                       limits = c("New Call", "Call Now\nAmbiguous", "Same Call"),
                                       labels = c("Incorrect\nPrediction", "No\nPrediction", "Same\nPrediction"))


```

```{r}
############################################################################
###                             Figure 4B                                ###
############################################################################

### Setting the seed and extracting the pre-filtered data from 3A
set.seed(40)

contigs <- threeA[[1]]
obj <- threeA[[2]]

### Finding suitable barcodes and filtering down to barcodes that were doublets
suitable_barcodes <- (cd8s@meta.data %>% filter(suitable) %>% select(Cell_barcode))$Cell_barcode

### Giving them a unique key for joining, before removing unsuitable cells.
contigs <- contigs %>% unite(c(barcode, cdr3), sep = "_", remove = FALSE, col = "key")
n_distinct(contigs$key) == nrow(contigs)
contigs <- contigs %>% distinct(key) %>% mutate(pos = sample.int(n())) %>% left_join(contigs, by = "key")
contigs$suitable <- contigs$barcode %in% suitable_barcodes

### Considering only contigs that aren't doublets and have the lowest pos variable in their cell which is used for randomization. This ensures 2 contigs aren't removed from the same cell.
### Then selecting only 500 contigs to add and retaining the meta data
contigs2 <- contigs %>% filter(barcode %in% cd8s$Cell_barcode) %>%
                        group_by(barcode) %>% filter(pos == min(pos)) %>% ungroup() %>%
                        filter(suitable) %>% arrange(desc(pos))
new_bc <- contigs2 %>% filter(row_number() <= 500)

### Making new_meta which is the meta data for the 500 random contig barcode. This is necessary because I can't just swap the barcode, then it will get messed up because the analysis is grouped by sample. The sample of the new barcode must match
### Making new_bc to only be the barcodes from the 500 contigs.
new_meta <- new_bc %>% select(barcode, "new_index" = index, "new_donor" = donor, "new_tissue" = tissue)
new_bc <- new_bc$barcode

### Taking 500 more random contigs and changing the barcodes to be from the first 500 random barcodes
new_contigs <- contigs2 %>% filter(row_number() > 500 & row_number() <= 1000)
new_contigs$barcode <- new_bc

### Modifying the second 500 to have the metadata from the first 500. Then removing the extra columns and changing the contig_id so it isn't duplicated
new_contigs <- new_contigs %>% left_join(new_meta, by = "barcode")
new_contigs$index <- new_contigs$new_index
new_contigs$donor <- new_contigs$new_donor
new_contigs$tissue <- new_contigs$new_tissue
new_contigs <- new_contigs %>% select(-new_index, -new_donor, -new_tissue)
new_contigs$contig_id <- paste(str_replace(new_contigs$barcode, "-.*$", ""), "-1_contig_1000000", sep = "") 

### Then taking these 500 random contigs which were given a random barcode/meta data set and adding them to the original contigs
contigs3 <- rbind(contigs, new_contigs)
contigs3 <- contigs3 %>% select(-pos, -key) %>% ungroup()

### Running the second half after the 500 new chains were added
pst2 <- post(folders = dirs, all = contigs3, seurat_object = obj, batch = "index", donor = "donor", group = "tissue", original_barcode = "Cell_Barcode", write_folder = "/home/ecb86/Desktop/braun/tcrEclipse/braun_cCell/tcr_temp", mode = "standard")
pst2 <- pst2 %>% select(Cell_barcode, "new_CTaa" = CTaa, "new_scrCTaa" = scR_CTaa, "newCloneCall" = cloneCallSource)

### adding the results to the original results
join_add <- cd8s@meta.data %>% left_join(pst2, by = "Cell_barcode")
join_add <- join_add %>% mutate(altered = case_when(
                                                     Cell_barcode %in% new_bc ~ TRUE,
                                                     !Cell_barcode %in% new_bc ~ FALSE),
                                steady = case_when(
                                                   CTaa == new_CTaa ~ "Same Call",
                                                   CTaa != new_CTaa & newCloneCall == "scRepertoire" ~ "Call Now\nAmbiguous",
                                           CTaa != new_CTaa & newCloneCall == "VDJdive" ~ "New Call"))

### Calculating the statistics
join2_add <- join_add %>% filter(!is.na(steady) & !is.na(altered)) %>% group_by(altered) %>% mutate(altered_count = n()) %>% ungroup() %>% 
                                                                       group_by(altered, steady) %>% summarise(pct = 100 * n() / first(altered_count),
                                                                                                               count = n(),
                                                                                                               altered_count = first(altered_count))
join2_add$steady <- factor(join2_add$steady, levels = c("New Call", "Call Now\nAmbiguous", "Same Call"))


join2_add %>% ggplot() + geom_col(aes(x = altered, y = pct, fill = steady)) + theme_classic() +
                         ylab("% of Cells") + xlab("TCR Chain\n Addition") +
                         theme(axis.title = element_text(size = 20, face = "bold"), legend.text = element_text(size = 14, face = "bold"), axis.ticks.x = element_blank(),
                               legend.title = element_text(face = "bold", size = 14), axis.text = element_text(size = 14, face = "bold"), axis.text.x = element_text(size = 24, face = "bold")) +
                         scale_y_continuous(expand = c(0.01, 0.01), breaks = seq(0, 100, 10), labels = c(0, "", 20, "", 40, "", 60, "", 80, "", 100)) + 
                         labs(fill = "Impact on\nPredicted\nClonotype") + scale_x_discrete(labels = c("-", "+")) +
                         scale_fill_manual(values = c("yellow3", "chartreuse4", "dodgerblue4"),
                                       limits = c("New Call", "Call Now\nAmbiguous", "Same Call"),
                                       labels = c("Incorrect\nPrediction", "No\nPrediction", "Same\nPrediction"))


```


```{r}
############################################################################
###                             Figure 4C                                ###
############################################################################

cd8s@meta.data <- cd8s@meta.data %>% mutate(clusters2 = case_when(
                                                                  str_detect(ClusterName_TCells, "CD8 TRM") ~ "Resident\nMemory",
                                                                  str_detect(ClusterName_TCells, "^Exhausted") ~ "Exhausted",
                                                                  str_detect(ClusterName_TCells, "Cytotoxic") ~ "Cytotoxic",
                                                                  str_detect(ClusterName_TCells, "erminally") ~ "Terminally\nExhausted",
                                                                  str_detect(ClusterName_TCells, "Proliferating") ~ "Proliferating"))

### 2000x500
threeC_results <- compareClones(cd8s, clusters = "clusters2", cloneThresh = 100, cloneClassThresh = 10)
df <- threeC_results[[1]]
plot3c <- threeC_results[[2]]

plot3c %>% ggplot(aes(x = class, y = Pct)) + 
           geom_line(aes(group = CTaa, color = CTaa)) +
           geom_point(aes(color = CTaa)) + facet_wrap(~clusters, nrow = 2) + theme_bw() + 
           theme(legend.position = "none", axis.text = element_text(size = 14, face = "bold"), axis.title = element_text(size = 20, face = "bold"),
                 panel.grid.minor = element_blank(), panel.grid.major = element_blank(), strip.text = element_text(face = "bold", size = 20), strip.background = element_rect(fill = "lightcoral")) + 
           scale_x_discrete(limits = c("1°", "1°\n&\n2°", "2°", "NA"),
                            labels = c("#1", "#2", "#3", "#4")) +
           ylab("% of Cells") + 
           xlab("Bitypic Chain Set")

          
```

```{r}
############################################################################
###                             Figure 4D                                ###
############################################################################
set.seed(16)
threeD_results <- compareClones(cd8s, clusters = "ClusterName_TCells", cloneThresh = 100, cloneClassThresh = 10)
df <- threeD_results[[1]]
plot3d <- threeD_results[[2]]


perm <- clusterPermutationTest1v2(cd8s, tcr = df, minCells = 10, clusters = "ClusterName_TCells")

perm_diffs <- perm[[1]]
mean_diff <- perm[[2]]

label <- case_when(sum(perm_diffs <= mean_diff) == 0 ~ "p < 0.0001",
                   sum(perm_diffs <= mean_diff) != 0 ~ paste("p = ", sum(perm_diffs <= mean_diff) / length(perm_diffs), sep = ""))


ggplot() + geom_histogram(aes(x = perm_diffs, fill = "Randomly\nPermuted\nClones"), bins = 90) + geom_vline(aes(xintercept = mean_diff, color = "Observed\n3 TCR Chain\nClones"), lwd = 2, linetype = "dotted") +
                                  annotate("text", x = 0.35, y = 250, label = label, fontface = 2, size = 6) +
                                  ggtitle("Cluster Usage", subtitle = "Expression of Bitypic Major vs. Minor Chain") + theme_classic() +  
                                  coord_cartesian(xlim = c(0, 1.05), ylim = c(0, 390), clip = "off") + xlab("Cluster Distribution Dissimilarity\n[Average Total Variation Distance]") + ylab("Number of Permutations") +
                                  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 24), axis.text = element_text(size = 14, face = "bold"), 
                                        legend.spacing.y = unit(0.05, "cm"), legend.margin = margin(-0.25, -0.25, 0, 0, "cm"), axis.title = element_text(size = 20, face = "bold"), 
                                        legend.text = element_text(size = 16, face = "bold"), plot.subtitle = element_text(hjust = 0.5, size = 16), legend.position = c(0.9, 0.8), 
                                        plot.margin = unit(c(1, 0, 3, 0), "lines"), axis.title.x = element_text(vjust = -7)) + 
                                  scale_y_continuous(expand = c(0, 0)) + labs(fill = "", color = "") +
                                  scale_fill_manual(values = c("Randomly\nPermuted\nClones" = "darkcyan")) + 
                                  scale_color_manual(values = c("Observed\n3 TCR Chain\nClones" = "darkorange3")) +
                                  annotate("text", x = 0.12, y = -30, label = "<-- Perfect Similarity", fontface = 2, size = 4) +
                                  annotate("text", x = 0.87, y = -30, label = "Perfect Dissimilarity -->", fontface = 2, size = 4)
                                  
                                 

```


```{r}
############################################################################
###                             Figure 4E                                ###
############################################################################
set.seed(16)
perm2 <- clusterPermutationTestMissing(cd8s, tcr = df, minCells = 10, clusters = "ClusterName_TCells")

perm_diffs2 <- perm2[[1]]
mean_diff2 <- perm2[[2]]

label <- case_when(sum(perm_diffs2 <= mean_diff2) == 0 ~ "p < 0.0001",
                   sum(perm_diffs2 <= mean_diff2) != 0 ~ paste("p = ", sum(perm_diffs2 <= mean_diff2) / length(perm_diffs2), sep = ""))
              

ggplot() + geom_histogram(aes(x = perm_diffs2, fill = "Randomly\nPermuted\nClones"), bins = 200) + geom_vline(aes(xintercept = mean_diff, color = "Observed\nClones"), lwd = 2, linetype = "dotted") +
                                  annotate("text", x = 0.35, y = 250, label = label, fontface = 2, size = 6) +
                                  ggtitle("Cluster Usage", subtitle = "Expression of Both vs. 1 Chain") + theme_classic() +  
                                  coord_cartesian(xlim = c(0, 1.05), ylim = c(0, 400), clip = "off") + xlab("Cluster Distribution Dissimilarity\n[Average Total Variation Distance]") + ylab("Number of Permutations") +
                                  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 24), axis.text = element_text(size = 14, face = "bold"), 
                                        legend.spacing.y = unit(0.05, "cm"), legend.margin = margin(-0.25, -0.25, 0, 0, "cm"), axis.title = element_text(size = 20, face = "bold"), 
                                        legend.text = element_text(size = 16, face = "bold"), plot.subtitle = element_text(hjust = 0.5, size = 16), legend.position = c(0.9, 0.8), 
                                        plot.margin = unit(c(1, 0, 3, 0), "lines"), axis.title.x = element_text(vjust = -7)) + 
                                  scale_y_continuous(expand = c(0, 0)) + labs(fill = "", color = "") +
                                  scale_fill_manual(values = c("Randomly\nPermuted\nClones" = "darkcyan")) + 
                                  scale_color_manual(values = c("Observed\nClones" = "darkorange3")) +
                                  annotate("text", x = 0.12, y = -30, label = "<-- Perfect Similarity", fontface = 2, size = 4) +
                                  annotate("text", x = 0.87, y = -30, label = "Perfect Dissimilarity -->", fontface = 2, size = 4)


```

