---
title: "figure3"
output: html_document
date: "2025-09-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(Seurat)
library(scRepertoire)
library(VDJdive)
library(rstatix)
library(readxl)
library(ggpubr)
library(ggsci)
library(RColorBrewer)
library(viridis)

source("/home/Desktop/R_tools/ECLIPSE.R")
source("/home/Desktop/R_tools/VDJdive_ECLIPSE_paperFunctions.R")
set.seed(16)
```

```{r}
############################################################################
###                         Pre-Processing                               ###
############################################################################

braun <- readRDS("/home/Desktop/braun/rotation/Braun_cancer_cell/scRCC_SeuratObject.rds")

braun@meta.data <- braun@meta.data %>% separate(Sample, into = c("donor", "tissue"), remove = FALSE, sep = "_")
braun@meta.data <- braun@meta.data %>% mutate(tissue = case_when(
                                                                 tissue %in% c("T", "T2") ~ "Tumor",
                                                                 tissue == "N" ~ "Normal",
                                                                 tissue %in% c("M", "V")  ~ "Other"))

cd8 <- subset(braun, subset = ClusterName_TCells %in% c("Treg", "Activated CD4.1", "Activated CD4.2", "CD4 TCM.1", "CD4 TCM.2", "Mito-high T cells", "-1"), invert = TRUE)

dirs <- list.files("/gpfs/gibbs/pi/braun/braun_cancerCell/realignment", recursive = TRUE, pattern = "all_contig_annotations\\.csv$", full.names = TRUE)
dirs <- dirs[!str_detect(dirs, "SC_VDJ_ASSEMBLER_CS")]
dirs <- str_replace(dirs, "all.*$", "")

matching <- read.csv("/home/project/david/sc_datasets/braun_cancer_cell/braun_matching2.csv")
matching <- matching %>% filter(Sample != "")

cd8@meta.data <- cd8@meta.data %>% left_join(matching[, 2:3], by = "Sample")
cd8@meta.data <- as.data.frame(cd8@meta.data)
rownames(cd8@meta.data) <- cd8$Cell_barcode
cd8$Cell_Barcode <- str_replace(cd8$Cell_barcode, "\\-.*$", "-1")

ElbowPlot(cd8, ndims = 50)
cd8 <- RunUMAP(cd8, dims = 1:30)

cd8$ClusterName_TCells[cd8$ClusterName_TCells == "PMCH+ terminally Exhausted CD8.1"] <- "PMCH+ terminally \n Exhausted CD8.1"
cd8$ClusterName_TCells[cd8$ClusterName_TCells == "Terminally exhausted CD8.2"] <- "Terminally \n exhausted CD8.2"
cd8$ClusterName_TCells[cd8$ClusterName_TCells == "Terminally exhausted CD8.3"] <- "Terminally \n exhausted CD8.3"

cd8s <- ECLIPSE(folders = dirs, file_type = "all", seurat_object = cd8, batch = "index", donor = "donor", group = "donor", original_barcode = "Cell_Barcode", write_folder = "/home/Desktop/braun/ECLIPSE/braun_cCell/tcr_temp", mode = "standard")

cd8s <- tcrDoubletDetect(cd8s)

```


```{r}
############################################################################
###                             Figure 3A                                ###
############################################################################

cd8s$cloneCallSource <- factor(cd8s$cloneCallSource, levels = c("VDJdive", "scRepertoire", NA))
### 500x500
DimPlot(cd8s, group.by = "cloneCallSource", pt.size = 1) + 
        theme_void() + ggtitle("") + scale_color_manual(limits = c("VDJdive", "scRepertoire", NA), values = c("sienna3", "slateblue", "grey70"), labels = c("Resolved", "Ambiguous", "No TCR\nDetected")) +
        theme(legend.text = element_text(face = "bold", size = 14), legend.title = element_text(size = 16, face = "bold")) +
        guides(color = guide_legend(nrow = 3, override.aes = list(size = 5), keywidth = 0.01, title = "Clonal Status"))


```

```{r}
############################################################################
###                             Figure 3B                                ###
############################################################################
df <- cd8s@meta.data %>% mutate(specialClone = case_when(
                                                         cloneCallSource == "VDJdive" & str_detect(CTaa, ":::.*_") ~ "Extra TCRα",
                                                         cloneCallSource == "VDJdive" & str_detect(CTaa, "_.*:::") ~ "Extra TCRβ",
                                                         cloneCallSource == "VDJdive" & !str_detect(CTaa, ":::") ~ "Regular",
                                                         cloneCallSource == "scRepertoire" ~ "Ambiguous",
                                                         is.na(cloneCallSource) ~ "No TCR\nDetected"))


df2 <- df %>% group_by(donor) %>% mutate(donorCount = n()) %>% ungroup() %>%
              group_by(donor, specialClone) %>% summarise(percent = 100 * n() / first(donorCount), donorCount = first(donorCount), count = n()) %>% ungroup()
df2$specialClone <- factor(df2$specialClone, levels = c("No TCR\nDetected", "Ambiguous", "Extra TCRα", "Extra TCRβ", "Regular"))

df2 <- df2 %>% group_by(donor) %>% mutate(regularSize = percent[which(specialClone == "Regular")]) %>% ungroup()
 
### 500x650
df2 %>% ggplot(aes(x = reorder(donor, -regularSize), y = percent)) + geom_bar(aes(fill = specialClone), stat = "identity") + 
        theme_classic() + xlab("Patient") + ylab("% of Cells") + labs(fill = "") +
        theme(axis.text = element_text(size = 14, face = "bold"), axis.title = element_text(size = 20, face = "bold"), legend.text = element_text(size = 14, face = "bold"), 
              legend.title = element_text(size = 16, face = "bold"), axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_text(vjust = 0.5)) + 
        guides(fill = guide_legend(nrow = 5)) + scale_y_continuous(expand = c(0.01, 0.01), breaks = seq(0, 100, 10), labels = c("0", "", "20", "", "40", "", "60", "", "80", "", "100")) +
        scale_fill_locuszoom(limits = c("No TCR\nDetected", "Ambiguous", "Extra TCRα", "Extra TCRβ", "Regular"),
                             labels = c("No TCR\nDetected", "Ambiguous\nChain Count", "Extra TCRα", "Extra TCRβ", "1 TCRα &\n1 TCRβ"))
  


### Finding medians/max/min for paper
df2_totals <- df2 %>% group_by(donor) %>% summarise(pct3 = sum(percent[specialClone %in% c("Extra TCRα", "Extra TCRβ")]))

median(df2_totals$pct3)
max(df2_totals$pct3)
min(df2_totals$pct3)
```


```{r}
############################################################################
###                             Figure 3C                                ###
############################################################################

### 300x500
df3 <- df2 %>% complete(donor, specialClone)
df3$percent[is.na(df3$percent)] <- 0

df3 %>% filter(specialClone %in% c("Extra TCRα", "Extra TCRβ")) %>%
        ggplot(aes(x = specialClone, y = percent)) + 
        geom_boxplot(aes(fill = specialClone), outlier.size = -1, lwd = 1.2, color = "black", width = 0.4) +
        geom_line(aes(group = donor), position = position_jitter(width = 0.15, seed = 70), color = "grey50", alpha = 0.3) +
        geom_point(position = position_jitter(width = 0.15, seed = 70), color = "grey40", fill = "white", shape = 21, stroke = 1, size = 2) +
        theme_classic() + labs(fill = "") + xlab("") + ylab("% of Cells") +
        theme(legend.position = "none", axis.text = element_text(size = 14, face = "bold"), axis.title = element_text(size = 20, face = "bold"), 
              axis.ticks.x = element_blank(), axis.text.x = element_text(vjust = -0.5)) + 
        scale_fill_manual(values = c("#5CB85CFF", "#46B8DAFF")) +
        stat_compare_means(comparison = list(c("Extra TCRα", "Extra TCRβ")), paired = TRUE)

paired_df <- df3 %>%
                    filter(specialClone %in% c("Extra TCRα", "Extra TCRβ")) %>%
                    select(donor, specialClone, percent) %>%
                    pivot_wider(
                                names_from = specialClone,
                                values_from = percent)
                    
wilcox.test(paired_df$`Extra TCRα`, paired_df$`Extra TCRβ`, paired = TRUE)




### Percentages for the paper
median(paired_df$`Extra TCRα`)
median(paired_df$`Extra TCRβ`)
```

```{r}
############################################################################
###                             Figure 3D                                ###
############################################################################

df3$count[is.na(df3$count)] <- 0

new_df <- df3 %>% filter(specialClone %in% c("Extra TCRα", "Extra TCRβ", "Regular")) %>%
                  group_by(donor) %>% mutate(donorCount2 = sum(count)) %>% ungroup() %>% 
                  mutate(percent = 100 * count / donorCount2)
paired_df <- new_df %>%
                       filter(specialClone %in% c("Extra TCRα", "Extra TCRβ")) %>%
                       select(donor, specialClone, percent) %>%
                       pivot_wider(
                                    names_from = specialClone,
                                    values_from = percent)                    

colnames(paired_df)[2] <- "Alpha"
colnames(paired_df)[3] <- "Beta"

paired_df <- paired_df %>% arrange(Alpha) %>% mutate(alpha_rank = row_number()) %>%
                           arrange(Beta) %>% mutate(beta_rank = row_number())


### 500x500
paired_df %>% ggplot(aes(x = Alpha, y = Beta)) + 
              geom_point() + 
              geom_smooth(method = "lm", color = "darkviolet", se = FALSE) + 
              theme_classic() + xlab("Extra TCRα\n(% of clonally resolved cells)") +
              ylab("Extra TCRβ\n(% of clonally resolved cells)") +
              stat_cor(method = "spearman", size = 5, color = "darkviolet", label.y = 9, label.x = 2, fontface = "bold", cor.coef.name = "rho") +
              theme(axis.text = element_text(size = 14, face = "bold"), axis.title = element_text(size = 16, face = "bold"))


```

```{r}
############################################################################
###                             Figure 3G                                ###
############################################################################

cd8 <- subset(braun, subset = ClusterName_TCells %in% c("Treg", "Activated CD4.1", "Activated CD4.2", "CD4 TCM.1", "CD4 TCM.2", "Mito-high T cells", "-1"), invert = TRUE)

cd8@meta.data <- cd8@meta.data %>% left_join(matching[, 2:3], by = "Sample")
cd8@meta.data <- as.data.frame(cd8@meta.data)
rownames(cd8@meta.data) <- cd8$Cell_barcode
cd8$Cell_Barcode <- str_replace(cd8$Cell_barcode, "\\-.*$", "-1")

ElbowPlot(cd8, ndims = 50)
cd8 <- RunUMAP(cd8, dims = 1:30)

cd8$ClusterName_TCells[cd8$ClusterName_TCells == "PMCH+ terminally Exhausted CD8.1"] <- "PMCH+ terminally \n Exhausted CD8.1"
cd8$ClusterName_TCells[cd8$ClusterName_TCells == "Terminally exhausted CD8.2"] <- "Terminally \n exhausted CD8.2"
cd8$ClusterName_TCells[cd8$ClusterName_TCells == "Terminally exhausted CD8.3"] <- "Terminally \n exhausted CD8.3"

screp <- scRep(cd8, folders = dirs, batch = "index", group = "tissue", original_barcode = "Cell_Barcode", mode = "standard")
noNaFilterMulti <- scRep(cd8, folders = dirs, batch = "index", group = "tissue", original_barcode = "Cell_Barcode", mode = "noNaFilterMulti")
noNaNoMulti <- scRep(cd8, folders = dirs, batch = "index", group = "tissue", original_barcode = "Cell_Barcode", mode = "noNaNoMulti")

tcre <- cd8s@meta.data %>% select(barcode, donor, CTaa, cloneCallSource) %>% mutate(type = "tcrEclipse")
scr <- screp@meta.data %>% select(barcode, donor, CTaa) %>% mutate(cloneCallSource = "scRepertoire") %>% mutate(type = "scRepertoire")
scr2 <- noNaFilterMulti@meta.data %>% select(barcode, donor, CTaa) %>% mutate(cloneCallSource = "scRepertoire") %>% mutate(type = "noNaFilterMulti")
scr3 <- noNaNoMulti@meta.data %>% select(barcode, donor, CTaa) %>% mutate(cloneCallSource = "scRepertoire") %>% mutate(type = "noNaNoMulti")

combo <- rbind(tcre, scr, scr2, scr3)
 
tcre_div <- clonalDiversity(cd8s, group.by = "donor", cloneCall = "aa", exportTable = TRUE) %>% mutate(class = "tcrEclipse")
scr_div <- clonalDiversity(screp, group.by = "donor", cloneCall = "aa", exportTable = TRUE) %>% mutate(class = "scRepertoire")
scr2_div <- clonalDiversity(noNaFilterMulti, group.by = "donor", cloneCall = "aa", exportTable = TRUE) %>% mutate(class = "noNaFilterMulti")
scr3_div <- clonalDiversity(noNaNoMulti, group.by = "donor", cloneCall = "aa", exportTable = TRUE) %>% mutate(class = "noNaNoMulti")

div <- rbind(tcre_div, scr_div, scr2_div, scr3_div)

div$class <- factor(div$class, levels = c("tcrEclipse", "scRepertoire", "noNaFilterMulti", "noNaNoMulti"))

div2 <- div %>% ungroup() %>% 
                    select(shannon, class, donor)  %>%
                    pivot_wider(
                                names_from = class,
                                values_from = shannon)

results <- runPairedTests(div2, groups = c("tcrEclipse", "noNaNoMulti", "noNaFilterMulti", "scRepertoire"), adjustment_method = "fdr", runPaired = TRUE)
results$y.position <- c(4.6, 4.8, 5, 5, 5.2, 5.4)

div %>% ggplot(aes(x = class, y = shannon)) + geom_boxplot(aes(fill = class), outlier.size = -1, lwd = 0.9, color = "black", width = 0.4) +
                                              geom_path(aes(group = donor), alpha = 0.3) +
                                              geom_point(color = "grey40", fill = "white", shape = 21, stroke = 1, size = 2) + 
                                              theme_classic() + xlab("") + ylab("Shannon Index") +
                                              stat_pvalue_manual(results, tip.length = 0, side = 4, label = "p.adj2") +
                                              theme(axis.text = element_text(size = 14, face = "bold"), axis.text.x = element_blank(),
                                                    axis.title = element_text(size = 20, face = "bold"), axis.ticks.x = element_blank(),
                                                    legend.position = "none") +
                                              scale_fill_manual(values = c("paleturquoise3", "darkorange2", "darkolivegreen3", "hotpink2"))


```

```{r}
############################################################################
###                       Extended Data 1B-D                             ###
############################################################################
div3 <- div %>% ungroup() %>% 
                    select(inv.simpson, class, donor)  %>%
                    pivot_wider(
                                names_from = class,
                                values_from = inv.simpson)

results <- runPairedTests(div3, groups = c("tcrEclipse", "noNaNoMulti", "noNaFilterMulti", "scRepertoire"), adjustment_method = "fdr", runPaired = TRUE)
results$y.position <- c(46, 49, 52, 52, 55, 58)

### 600x500
div %>% ggplot(aes(x = class, y = inv.simpson)) + geom_boxplot(aes(fill = class), outlier.size = -1, lwd = 0.9, color = "black", width = 0.4) +
                                              geom_path(aes(group = donor), alpha = 0.3) +
                                              geom_point(color = "grey40", fill = "white", shape = 21, stroke = 1, size = 2) + 
                                              theme_classic() + xlab("") + ylab("Inverse Simpson Index") +
                                              stat_pvalue_manual(results, tip.length = 0, side = 4, label = "p.adj2") +
                                              theme(axis.text = element_text(size = 14, face = "bold"), axis.text.x = element_blank(),
                                                    axis.title = element_text(size = 20, face = "bold"), axis.ticks.x = element_blank(), 
                                                    legend.position = "none")  +
                                              scale_x_discrete(limits = c("tcrEclipse", "scRepertoire", "noNaFilterMulti", "noNaNoMulti"),
                                                               labels  = c("tcrEclipse", "Allow Missing\nAllow Multi", "No Missing\nAdjust Multi", "No Missing\nNo Multi")) +
                                              scale_fill_manual(values = c("paleturquoise3", "darkorange2", "darkolivegreen3", "hotpink2"))



div4 <- div %>% ungroup() %>% 
                    select(norm.entropy, class, donor)  %>%
                    pivot_wider(
                                names_from = class,
                                values_from = norm.entropy)

results <- runPairedTests(div4, groups = c("tcrEclipse", "noNaNoMulti", "noNaFilterMulti", "scRepertoire"), adjustment_method = "fdr", runPaired = TRUE)
results$y.position <- c(0.95, 0.98, 1.01, 1.01, 1.04, 1.07)

### 600x500
div %>% ggplot(aes(x = class, y = norm.entropy)) + geom_boxplot(aes(fill = class), outlier.size = -1, lwd = 0.9, color = "black", width = 0.4) +
                                              geom_path(aes(group = donor), alpha = 0.3) +
                                              geom_point(color = "grey40", fill = "white", shape = 21, stroke = 1, size = 2) + 
                                              theme_classic() + xlab("") + ylab("Normalized Entropy Index") +
                                              stat_pvalue_manual(results, tip.length = 0, side = 4, label = "p.adj2") +
                                              theme(axis.text = element_text(size = 14, face = "bold"), axis.text.x = element_blank(),
                                                    axis.title = element_text(size = 20, face = "bold"), axis.ticks.x = element_blank(),
                                                    legend.position = "none")  +
                                              scale_x_discrete(limits = c("tcrEclipse", "scRepertoire", "noNaFilterMulti", "noNaNoMulti"),
                                                               labels  = c("tcrEclipse", "Allow Missing\nAllow Multi", "No Missing\nAdjust Multi", "No Missing\nNo Multi")) +
                                              scale_fill_manual(values = c("paleturquoise3", "darkorange2", "darkolivegreen3", "hotpink2"))





div5 <- div %>% ungroup() %>% 
                    select(gini.simpson, class, donor)  %>%
                    pivot_wider(
                                names_from = class,
                                values_from = gini.simpson)

results <- runPairedTests(div5, groups = c("tcrEclipse", "noNaNoMulti", "noNaFilterMulti", "scRepertoire"), adjustment_method = "fdr", runPaired = TRUE)
results$y.position <- c(1, 1.02, 1.04, 1.04, 1.06, 1.08)

### 600x500
div %>% ggplot(aes(x = class, y = gini.simpson)) + geom_boxplot(aes(fill = class), outlier.size = -1, lwd = 0.9, color = "black", width = 0.4) +
                                              geom_path(aes(group = donor), alpha = 0.3) +
                                              geom_point(color = "grey40", fill = "white", shape = 21, stroke = 1, size = 2) + 
                                              theme_classic() + xlab("") + ylab("Gini-Simpson Index") +
                                              stat_pvalue_manual(results, tip.length = 0, side = 4, label = "p.adj2") +
                                              theme(axis.text = element_text(size = 14, face = "bold"), axis.text.x = element_blank(),
                                                    axis.title = element_text(size = 20, face = "bold"), axis.ticks.x = element_blank(),
                                                    legend.position = "none")  +
                                              scale_x_discrete(limits = c("tcrEclipse", "scRepertoire", "noNaFilterMulti", "noNaNoMulti"),
                                                               labels  = c("tcrEclipse", "Allow Missing\nAllow Multi", "No Missing\nAdjust Multi", "No Missing\nNo Multi")) +
                                              scale_fill_manual(values = c("paleturquoise3", "darkorange2", "darkolivegreen3", "hotpink2"))


```


```{r}
############################################################################
###                             Figure 3F                                ###
############################################################################
combo2 <- combo %>% group_by(donor, type) %>% mutate(totalCount = n()) %>% ungroup() %>%
                    group_by(donor, type, CTaa) %>% summarise(count = n(),
                                                              pct = 100 * n() / first(totalCount),
                                                              total = first(totalCount))

combo2 <- combo2 %>% filter(!is.na(CTaa)) %>% arrange(desc(count)) %>% group_by(donor, type) %>% filter(row_number() <= 30) %>% ungroup()

combo3 <- combo2 %>% group_by(donor, type) %>% summarise(mn = mean(count)) %>% ungroup()

combo3$type <- factor(combo3$type, levels = c("tcrEclipse", "scRepertoire", "noNaFilterMulti", "noNaNoMulti"))
combo3 <- combo3 %>% group_by(donor) %>% mutate(pct = (100 * mn / mn[which(type == "noNaNoMulti")]) - 100)
combo3 <- combo3 %>% arrange(type)

combo4 <- combo3 %>% ungroup() %>% 
                    select(type, pct, donor)  %>%
                    pivot_wider(
                                names_from = type,
                                values_from = pct)

results <- runPairedTests(combo4, groups = c("tcrEclipse", "noNaNoMulti", "noNaFilterMulti", "scRepertoire"), adjustment_method = "fdr", runPaired = TRUE)
results$y.position <- c(92, 99, 106, 106, 113, 121)

### 700x550
combo3 %>% ggplot(aes(x = type, y = pct)) + geom_boxplot(aes(fill = type), outlier.size = -1, lwd = 0.9, color = "black", width = 0.4) +
                                                 geom_path(aes(group = donor), alpha = 0.3) +
                                                 geom_point(color = "grey40", fill = "white", shape = 21, stroke = 1, size = 2) + 
                                                 theme_classic() + xlab("") + ylab("% Change in Mean Size of\n Top 30 Clones") +
                                                 stat_pvalue_manual(results, tip.length = 0, side = 4, label = "p.adj2") +
                                                 theme(axis.text = element_text(size = 14, face = "bold"), axis.text.x = element_blank(),
                                                       axis.title = element_text(size = 20, face = "bold"), axis.ticks.x = element_blank(),
                                                       legend.position = "none")  +
                                                 scale_fill_manual(values = c("paleturquoise3", "darkorange2", "darkolivegreen3", "hotpink2"))




### Stats for paper
combo3 %>% group_by(type) %>% summarise(med = median(pct))
max(combo3$pct[combo3$type == "tcrEclipse"])

```

```{r}
############################################################################
###                         Extended Data 1A                             ###
############################################################################
combo5 <- combo %>% group_by(donor, type) %>% mutate(totalCount = n()) %>% ungroup() %>%
                    group_by(donor, type, CTaa) %>% summarise(count = n(),
                                                              pct = 100 * n() / first(totalCount),
                                                              total = first(totalCount))


combo5 <- combo5 %>% filter(!is.na(CTaa)) %>% arrange(desc(count)) %>% group_by(donor, type) %>% filter(row_number() <= 60 & row_number() > 30) %>% ungroup()

combo6 <- combo5 %>% group_by(donor, type) %>% summarise(mn = mean(count)) %>% ungroup()

combo6$type <- factor(combo6$type, levels = c("tcrEclipse", "scRepertoire", "noNaFilterMulti", "noNaNoMulti"))
combo6 <- combo6 %>% group_by(donor) %>% mutate(pct = (100 * mn / mn[which(type == "noNaNoMulti")]) - 100)
combo6 <- combo6 %>% arrange(type)


combo7 <- combo6 %>% ungroup() %>% 
                    select(type, pct, donor)  %>%
                    pivot_wider(
                                names_from = type,
                                values_from = pct)

results <- runPairedTests(combo7, groups = c("tcrEclipse", "noNaNoMulti", "noNaFilterMulti", "scRepertoire"), adjustment_method = "fdr", runPaired = TRUE)
results$y.position <- c(90, 95, 100, 100, 105, 110)

### 700x550
combo6 %>% ggplot(aes(x = type, y = pct)) + geom_boxplot(aes(fill = type), outlier.size = -1, lwd = 0.9, color = "black", width = 0.4) +
                                                 geom_path(aes(group = donor), alpha = 0.3) +
                                                 geom_point(color = "grey40", fill = "white", shape = 21, stroke = 1, size = 2) + 
                                                 theme_classic() + xlab("") + ylab("% Change in Mean Size of\n 31-60 Biggest Clones") +
                                                 stat_pvalue_manual(results, tip.length = 0, side = 4, label = "p.adj2") +
                                                 theme(axis.text = element_text(size = 14, face = "bold"), axis.text.x = element_blank(),
                                                       axis.title = element_text(size = 20, face = "bold"), axis.ticks.x = element_blank(),
                                                       legend.position = "none")  +
                                                 scale_fill_manual(values = c("paleturquoise3", "darkorange2", "darkolivegreen3", "hotpink2"))



```



```{r}
############################################################################
###                             Figure 3E                                ###
############################################################################
combo <- combo %>% mutate(missing = case_when(
                                               is.na(CTaa) ~ "No TCR\nDetected",
                                              !is.na(CTaa) ~ "Not Missing"))
combo4 <- combo %>% group_by(donor, type) %>% mutate(totalCount = n()) %>% ungroup() %>%
                    group_by(donor, type, missing) %>% summarise(count = n(),
                                                                 total = first(totalCount),
                                                                 pct = 100 * n() / first(totalCount))

combo5 <- combo4 %>% ungroup() %>% filter(missing == "No TCR\nDetected") %>% 
                    select(donor, type, pct) %>%
                    pivot_wider(
                                names_from = type,
                                values_from = pct)
                    
results <- runPairedTests(combo5, groups = c("tcrEclipse", "noNaNoMulti", "noNaFilterMulti", "scRepertoire"), adjustment_method = "fdr", runPaired = TRUE)
results$y.position <- c(45, 49, 53, 53, 57, 61)

combo4$type <- factor(combo4$type, levels = c("tcrEclipse", "scRepertoire", "noNaFilterMulti", "noNaNoMulti"))
combo4 <- combo4 %>% arrange(type)

combo4 <- combo4 %>% filter(missing == "No TCR\nDetected")

### 700x500
combo4 %>% ggplot(aes(x = type, y = pct)) + geom_boxplot(aes(fill = type), outlier.size = -1, lwd = 0.9, color = "black", width = 0.4) +
                                                 geom_path(aes(group = donor), alpha = 0.3) +
                                                 geom_point(color = "grey40", fill = "white", shape = 21, stroke = 1, size = 2) + 
                                                 theme_classic() + xlab("") + ylab("% of Cells\nWith Missing TCR Data") +
                                                 stat_pvalue_manual(results, tip.length = 0, side = 4, label = "p.adj2") +
                                                 theme(axis.text = element_text(size = 14, face = "bold"), axis.text.x = element_blank(),
                                                       axis.title = element_text(size = 20, face = "bold"), axis.ticks.x = element_blank(),
                                                       legend.position = "none") +
                                                 scale_fill_manual(values = c("paleturquoise3", "darkorange2", "darkolivegreen3", "hotpink2"))




### Stats for paper
combo4 %>% group_by(type) %>% summarise(md = median(pct))
```

